name: windows

on:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows]
        config: [Release]

    runs-on: ${{matrix.os}}-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
        fetch-depth: 1
        
    - name: Build Release
      run: make release
      
    - name: Test Release
      run: make test
      continue-on-error: true

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: windows-convimg
        path: bin/convimg.exe
